version: "3.9"

services:
  users-api:
    container_name: users-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres_users-api
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - users-api-network
      # - kafka_network

  postgres_users-api:
    container_name: postgres_users-api
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DBNAME}
    expose:
      - 5435
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - users-api-network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
  #     PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres_userprof
  #   networks:
  #     - auth-api-network

volumes:
  postgres_data:


networks:
  users-api-network:
  # kafka_network:
  #   external: true
  #   name: kafka_kafka_network
